import { Category } from "./Entities/Products/Category";
import { Company } from "./Entities/Common/Company";
import { Employee } from "./Entities/Employees/Employee";
import { InventoryAdjustment } from "./Entities/Inventory/InventoryAdjustment";
import { Location } from "./Entities/Inventory/Location";
import { Product } from "./Entities/Products/Product";
import { Quant } from "./Entities/Inventory/Quant";
import { Serial } from "./Entities/Inventory/Serial";
import { Warehouse } from "./Entities/Inventory/Warehouse";
import { Odoo } from "./Odoo";
import { OdooFactory } from "./OdooFactory";
import { OdooConfiguration } from "./Config/OdooConfiguration";
import { OdooCompany } from "./Config/OdooCompany";
import * as Api from "./API/api";
declare const Config: {
    OdooConfiguration: typeof OdooConfiguration;
    OdooCompany: typeof OdooCompany;
};
declare const Entities: {
    Category: typeof Category;
    Company: typeof Company;
    Employee: typeof Employee;
    InventoryAdjustment: typeof InventoryAdjustment;
    Location: typeof Location;
    Product: typeof Product;
    Quant: typeof Quant;
    Serial: typeof Serial;
    Warehouse: typeof Warehouse;
};
export { Api, Config, Entities, Odoo, OdooFactory };
